### ISSUE TITLE
Linux-64 chrome://settings consistently crashing latest Canary and Developer builds

### ISSUE THREAD

**Issue by guest271314** [GoogleChromeLabs/chrome-for-testing#78]

**Comment by mathiasbynens** [comment]
Is this CfT-specific, or does it happen for regular Chrome Canary / Dev builds as well?

**Comment by guest271314** [comment]
CfT-specific. Does not happen for Chromium from https://download-chromium.appspot.com/.

**Comment by thiagowfx** [comment]
Reproduced on 120.0.6095.0 (Canary) on Linux64.

**Comment by mathiasbynens** [comment]
Can haz bisect?

**Comment by guest271314** [comment]
What application in Chromium is using TensorFlow and why? 

If TensorFlow can be shipped in Chromium speech synthesis and speech recognition can be shipped in Chromium instead of making external requests to Google servers for Web Speech API.

**Comment by thiagowfx** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1494574

**Comment by guest271314** [comment]
Wait a minute. Am I reading that right? One of the first things I do is set my own search engine using an extension so everything I type in the Omnibox doesn't get forwarded to Google, at east that's the idea.

**Comment by guest271314** [comment]
For completeness this is what I have been doing for quite some time now (years).

```
{
  "name": "tab",
  "version": "1.0",
  "manifest_version": 3,
  "chrome_url_overrides" : {
    "newtab": "./tab.html"
  },
  "background": {
    "service_worker": "background.js"
  },
```

Recently I added a script to get rid of the redundant "My extensions" section of  chrome://extensions which takes up a third of the page. 

![Screenshot_2023-10-30_22-37-49](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/4174848/d1e6cd24-86b3-4dfd-9e7a-8508df134057)
![Screenshot_2023-10-30_22-38-10](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/4174848/ced8b7e1-d9d6-4250-af6c-1c4c85eccf43)
![Screenshot_2023-10-30_22-42-00](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/4174848/0cd59472-5844-4034-99ec-60bf51e0ccc4)
![Screenshot_2023-10-30_22-42-27](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/4174848/cafca481-d238-4019-b06f-54eef2526a49)


background.js
```
chrome.tabs.onUpdated.addListener(async (id, changeInfo, tab) => {
  if (
    changeInfo.status === "complete" &&
    tab.url.startsWith("chrome://extensions")
  ) {
    await chrome.scripting.executeScript({
      target: {
        tabId: id,
      },
      world: "MAIN",
      func: () => {
        document.querySelector("extensions-manager")
          .shadowRoot.getElementById("left").remove();
      },
    });
  }
});
```

**Comment by thiagowfx** [comment]
Should be fixed in the next release: https://bugs.chromium.org/p/chromium/issues/detail?id=1494574#c8

Thanks for your bug report!

> Wait a minute. Am I reading that right? One of the first things I do is set my own search engine using an extension so everything I type in the Omnibox doesn't get forwarded to Google, at east that's the idea.

No. I can see how the flag name can be confusing without context. What you are describing should still be possible, this flag controls something else.

**Comment by guest271314** [comment]
Just so we are on the same page, what is the version of the next release this is supposed to be fixed on?

chrome-for-testing/120.0.6099.2/linux64 is still crashing. Now also when I try to navigate to chrome://version .

**Comment by guest271314** [comment]
chrome://settings does not crash the browser on chrome-for-testing/121.0.6101.0/linux64.

**Comment by mathiasbynens** [comment]
Thanks for verifying!

**Comment by guest271314** [comment]
FYI same issue is showing up on Chromium Developer Build 121.0.6114.0, not on Chrome-For-Testing Version 121.0.6111.0 (Official Build) (64-bit).

**Comment by guest271314** [comment]
@mathiasbynens @thiagowfx 

Regression.

**Comment by guest271314** [comment]
I had 73 features listed in value for `--disable-features`. I deleted them one by one, launched Chrome-For-Testing Version 121.0.6124.0 (Official Build) (64-bit) and Chromium Version 121.0.6125.0 (Developer Build) (64-bit), navigated to `chrome://settings` until the browser no longer crashed. 

When `OptimizationHints` is set the browser crashes when navigating to `chrome://settings`.

**Comment by guest271314** [comment]
Just for completeness here's the road map to the crash when `--disable-feature=OptimizationHints` is passed as a flag

```
/launch_chromium.sh
[11494:11494:1112/165602.886307:ERROR:policy_logger.cc(156)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
[1112/165626.743806:ERROR:elf_dynamic_array_reader.h(64)] tag not found
Received signal 11 SEGV_MAPERR 000000000088
#0 0x562702fdc372 base::debug::CollectStackTrace()
#1 0x562702fc8a83 base::debug::StackTrace::StackTrace()
#2 0x562702fdbd91 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f514e560520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
#4 0x562702b0f984 OptimizationGuideKeyedService::IsSettingVisible()
#5 0x5627089b87e1 settings::SettingsUI::SettingsUI()
#6 0x562708847352 (anonymous namespace)::NewWebUI<>()
#7 0x56270152e370 content::WebUIControllerFactoryRegistry::CreateWebUIControllerForURL()
#8 0x56270128ce29 content::NavigationRequest::CreateWebUIIfNeeded()
#9 0x5627012fd4f9 content::RenderFrameHostManager::GetFrameHostForNavigation()
#10 0x5627012fcd81 content::RenderFrameHostManager::DidCreateNavigationRequest()
#11 0x5627011d566e content::FrameTreeNode::TakeNavigationRequest()
#12 0x56270129d5bd content::Navigator::Navigate()
#13 0x562701255d83 content::NavigationControllerImpl::NavigateWithoutEntry()
#14 0x5627012556af content::NavigationControllerImpl::LoadURLWithParams()
#15 0x5627088a6383 (anonymous namespace)::LoadURLInContents()
#16 0x5627088a53ce Navigate()
#17 0x5627089037d3 ShowSingletonTabOverwritingNTP()
#18 0x562708903876 ShowSingletonTabOverwritingNTP()
#19 0x5627088aaebe chrome::ShowAboutChrome()
#20 0x56270888fb6e chrome::BrowserCommandController::ExecuteCommandWithDisposition()
#21 0x562708bf43ee AppMenuModel::ExecuteCommand()
#22 0x5627051ce908 views::internal::MenuRunnerImpl::OnMenuClosed()
#23 0x5627051bc003 views::MenuController::ExitMenu()
#24 0x5627051bde37 views::MenuController::Accept()
#25 0x5627051bdb22 views::MenuController::OnMouseReleased()
#26 0x56270523849f views::Widget::OnMouseEvent()
#27 0x56270526411e views::DesktopNativeWidgetAura::OnMouseEvent()
#28 0x562703ada798 ui::EventDispatcher::ProcessEvent()
#29 0x562703ada468 ui::EventDispatcherDelegate::DispatchEventToTarget()
#30 0x562703ada29e ui::EventDispatcherDelegate::DispatchEvent()
#31 0x562705072fcc ui::EventProcessor::OnEventFromSource()
#32 0x56270507c28c ui::EventSource::DeliverEventToSink()
#33 0x56270507c1b4 ui::EventSource::SendEventToSinkFromRewriter()
#34 0x56270526b5ad aura::WindowTreeHostPlatform::DispatchEvent()
#35 0x562705269e1e views::DesktopWindowTreeHostLinux::DispatchEvent()
#36 0x562703ade557 ui::DispatchEventFromNativeUiEvent()
#37 0x5626ff0cb049 ui::X11Window::DispatchUiEvent()
#38 0x5626ff0cad28 ui::X11Window::DispatchEvent()
#39 0x5626ff0cb0fd ui::X11Window::DispatchEvent()
#40 0x562703ac37d9 ui::PlatformEventSource::DispatchEvent()
#41 0x5627043eff11 ui::X11EventSource::OnEvent()
#42 0x5626fec1b5a5 x11::Connection::DispatchEvent()
#43 0x5626fec1b366 x11::Connection::ProcessNextEvent()
#44 0x5626fec1afc9 x11::Connection::Dispatch()
#45 0x5627043f3d62 ui::(anonymous namespace)::XSourceDispatch()
#46 0x7f514f2a4c24 g_main_context_dispatch
#47 0x7f514f2f96f8 (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.1+0xaa6f7)
#48 0x7f514f2a23c3 g_main_context_iteration
#49 0x562702ff109b base::MessagePumpGlib::Run()
#50 0x562702f88a79 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#51 0x562702f4fe8a base::RunLoop::Run()
#52 0x562700d7540a content::BrowserMainLoop::RunMainMessageLoop()
#53 0x562700d76fd2 content::BrowserMainRunnerImpl::Run()
#54 0x562700d72576 content::BrowserMain()
#55 0x562702370fbd content::RunBrowserProcessMain()
#56 0x562702372860 content::ContentMainRunnerImpl::RunBrowser()
#57 0x56270237262c content::ContentMainRunnerImpl::Run()
#58 0x56270236fce8 content::RunContentProcess()
#59 0x56270236ff0d content::ContentMain()
#60 0x5626fe64931b ChromeMain
#61 0x7f514e547d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#62 0x7f514e547e40 __libc_start_main
#63 0x5626fe64902a _start
  r8: 00000a1401899420  r9: 00000a14024ff930 r10: 746369506f747561 r11: 6369506e49657275
 r12: 00000a1401442888 r13: 0000000000000000 r14: 00000a1401021740 r15: 00000a140097c800
  di: 0000000000000000  si: 0000000000000001  bp: 00007ffd29d67d60  bx: 0000000000000000
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000001  sp: 00007ffd29d67d60
  ip: 0000562702b0f984 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000088
[end of stack trace]
Segmentation fault (core dumped)
```

**Comment by mathiasbynens** [comment]
Cannot repro on macOS nor on Linux with CfT 121.0.6124.0:

```
$ npx @puppeteer/browsers install chrome@canary
Downloading chrome r121.0.6124.0 - 146.3 MB [====================] 100% 0.0s
chrome@121.0.6124.0 /private/tmp/chrome/mac_arm-121.0.6124.0/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing

$ ./chrome/mac_arm-121.0.6124.0/chrome-mac-arm64/Google\ Chrome\ for\ Testing.app/Contents/MacOS/Google\ Chrome\ for\ Testing  --disable-feature=OptimizationHints
[16616:259:1113/082440.396775:ERROR:policy_logger.cc(156)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
[16616:69891:1113/082440.421968:ERROR:login_database_async_helper.cc(102)] Encryption is not available.
[16616:80899:1113/082440.422062:ERROR:login_database_async_helper.cc(102)] Encryption is not available.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
WARNING: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#39 is a dynamic-sized tensor).
```

**Comment by guest271314** [comment]
@mathiasbynens Did you navigate to chrome://settings? Launching with the flag alone doesn't crash the browser. What happens when you click "About Google Chrome for Testing" or "Settings" or manually navigate to chrome://settings?

**Comment by guest271314** [comment]
@mathiasbynens Here's a screen capture

[48f8d968-04f0-415c-a045-9a312476b0bf.webm](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/4174848/b4013e02-fcbe-4135-b46c-88ab1643b02a)

**Comment by mathiasbynens** [comment]
> @mathiasbynens Did you navigate to chrome://settings? Launching with the flag alone doesn't crash the browser. What happens when you click "About Google Chrome for Testing" or "Settings" or manually navigate to chrome://settings?

In my above tests, I had manually navigated to `chrome://settings`. I just tried to go there via the three-dot menu like in your screen capture but that seems to work fine as well.

I wonder what else is unique about your setup that would let me repro it.

**Comment by mathiasbynens** [comment]
https://crbug.com/1476101

**Comment by guest271314** [comment]
> I wonder what else is unique about your setup that would let me repro it.

I don't know. Could be any number of factors. 

I know I started testing the `--disable-features` values because somebody over on Chromium-Dev groups board mention intent to _not_ allow people to turn off `InsecureDownloadWarnings`. If they want theat setting on they can use it on their own machine. So I started on that line in my Chromium launcher script I've been using for years now. It took me a couple dozen launches and crashes to isolate the cause in this case.  But you folks already knew about this per the bug marked fixed, right?

```
--disable-features=InsecureDownloadWarnings,SafeBrowsing,SafetyTip,ThirdPartyStoragePartitioning,CalculateNativeWinOcclusion,AudioFocusEnforcement,AutofillUpstream,AutofillUpstreamEditableCardholderName,CloudPrinterHandler,GenericSensorExtraClasses,OmniboxAutocompleteTitles,OmniboxDocumentProvider,OmniboxExperimentalKeywordMode,OmniboxExperimentalSuggestScoring,OmniboxGroupSuggestionsBySearchVsUrl,OmniboxLocalEntitySuggestions,OmniboxLooseMaxLimitOnDedicatedRows,OmniboxMaxURLMatches,OmniboxOnDeviceHeadProvider,OmniboxOnFocusSuggestions,OmniboxPedalSuggestions,OmniboxPreserveDefaultMatchAgainstAsyncUpdate,OmniboxRichEntitySuggestions,OmniboxShortBookmarkSuggestions,OmniboxSuggestionTransparencyOptions,OmniboxTabSwitchSuggestions,OmniboxTabSwitchSuggestionsDedicatedRow,OmniboxUIExperimentMaxAutocompleteMatches,OmniboxUIExperimentShowSuggestionFavicons,OmniboxZeroSuggestionsOnNTP,WebPaymentsExperimentalFeatures,fill-on-account-select \
```

**Comment by guest271314** [comment]
Aren't optimization hints just pop-ups in the browser UI describing Chrome features?

Seems like all of those features can be just written out in a chrome: page, e.g., chrome://settings/help is probably a reasonable place for that, so the user is no arbitrarily bombarded with pop-ups. 

Chrome-For-Testing Version 121.0.6147.0 (Official Build) (64-bit) is still crashing with `--disable-features=OptimizationHints`  flag.

**Comment by guest271314** [comment]
> No. I can see how the flag name can be confusing without context. What you are describing should still be possible, this flag controls something else.

Sure enough, on CfT Version 122.0.6190.0 (Official Build) (64-bit) we cannot change the default search engine to a user-defined search engine.
